---
title: "COVID-SEP project"
subtitle: "SEP diffs"
description: |
date: "`r Sys.Date()`"
author:
  - name: Radoslaw Panczak 
    url: https://github.com/RPanczak
    affiliation: ISPM
    affiliation_url: https://www.ispm.unibe.ch/
    orcid_id: 0000-0001-5141-683X
# bibliography: biblio.bib
output:
  distill::distill_article:
    highlight: pygments
    toc: true
    toc_depth: 1
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

<!-- ------------------------------------------------------------ --> 
<!-- ------------------------------------------------------------ --> 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(scipen=999)
set.seed(12345)
library(pacman) 
p_load(tidyverse, haven, magrittr, 
       scales, sjmisc, sjPlot, 
       sf, tmap)
tmap_mode("view")
```

# SEP indices

```{r}
sep3 <- read_rds("data/Swiss-SEP3/ssep3_user_geo.Rds") %>% 
  select(gisid, buildper2, ssep1, ssep1_d, ssep2, ssep2_d, ssep3, ssep3_d) %>%
  mutate(ssep1_d = factor(ssep1_d),
         ssep2_d = factor(ssep2_d),
         ssep3_d = factor(ssep3_d))

sep1 <- read_rds("data/Swiss-SEP1/ssep_user_geo.Rds") %>% 
  select(v0_buildid, ssep, ssep_d) %>% 
  rename(ssep1_old = ssep, 
         ssep1_d_old = ssep_d) %>% 
  mutate(ssep1_d_old = factor(ssep1_d_old)) %>% 
  st_transform(crs = 2056)
```

Using `r number(nrow(sep1), big.mark = ",")` n'hoods from version 1.0.
Using `r number(nrow(sep3), big.mark = ",")` n'hoods from version 3.0.

# Spatial linkage

To PLZ and cantons

```{r}
# join to PLZ 2020
plz_20_10 <- read_rds("data/PLZ/plz_20_10.Rds") 

plz_20_10_mp <- plz_20_10 %>% 
  group_by(PLZ) %>% 
  summarise(PLZ = first(PLZ)) %>%
  st_cast("MULTIPOLYGON") 

plz_20_10_centr <- st_centroid(plz_20_10_mp)

sep3 <- st_join(sep3, plz_20_10, join = st_intersects)
# sep3 %>% filter(is.na(PLZ))

# join to canton
canton_2020_01 <- read_rds("data/swissBOUNDARIES3D/canton_2020_01.Rds") %>% 
  select(-KT_TEIL)

sep3 <- st_join(sep3, canton_2020_01, join = st_intersects) %>% 
  mutate(
    canton = case_when(
      NAME == "Aargau" ~ "AG", 
      NAME == "Appenzell Ausserrhoden" ~ "AR", 
      NAME == "Appenzell Innerrhoden" ~ "AI", 
      NAME == "Basel-Landschaft" ~ "BL", 
      NAME == "Basel-Stadt" ~ "BS", 
      NAME == "Bern" ~ "BE", 
      NAME == "Fribourg" ~ "FR", 
      NAME == "Genève" ~ "GE", 
      NAME == "Glarus" ~ "GL", 
      NAME == "Graubünden" ~ "GR", 
      NAME == "Jura" ~ "JU", 
      NAME == "Luzern" ~ "LU", 
      NAME == "Neuchâtel" ~ "NE", 
      NAME == "Nidwalden" ~ "NW", 
      NAME == "Obwalden" ~ "OW", 
      NAME == "Schaffhausen" ~ "SH", 
      NAME == "Schwyz" ~ "SZ", 
      NAME == "Solothurn" ~ "SO", 
      NAME == "St. Gallen" ~ "SG", 
      NAME == "Thurgau" ~ "TG", 
      NAME == "Ticino" ~ "TI", 
      NAME == "Uri" ~ "UR", 
      NAME == "Valais" ~ "VS", 
      NAME == "Vaud" ~ "VD", 
      NAME == "Zug" ~ "ZG", 
      NAME == "Zürich" ~ "ZH")) %>% 
  mutate(
    canton2 = canton,
    canton2 = ifelse(canton == "AI" | canton == "AR", "AI/AR", canton2),
    canton2 = ifelse(canton == "OW" | canton == "NW", "OW/NW", canton2)) %>% 
  mutate(diff = if_else(ssep1_d != ssep3_d, 1, 0)) 

rm(canton_2020_01)
# sep3 %>% filter(is.na(KANTONSNUM))

# View(st_drop_geometry(sep3))
# sjmisc::frq(sep3$canton, sort.frq = "desc")

sjmisc::frq(sep3$diff)

write_rds(sep3, "data/Swiss-SEP3/sep3_diff.rds")
gc()
```


# Factors associated with change

## Canton 

```{r}
fit1 <- glm(diff ~ as.factor(canton),  data = st_drop_geometry(sep3), family = binomial())

summary(fit1)
plot_model(fit1, axis.lim = c(0.1, 2))
tab_model(fit1)
```

## SEP1 decile

```{r}
fit2 <- glm(diff ~ as.factor(ssep1_d), data = st_drop_geometry(sep3), family = binomial())

summary(fit2)
plot_model(fit2)#, axis.lim = c(0.1, 2))
tab_model(fit2)
```

## SEP3 decile

```{r}
fit3 <- glm(diff ~ as.factor(ssep3_d), data = st_drop_geometry(sep3), family = binomial())

summary(fit3)
plot_model(fit3)#, axis.lim = c(0.1, 2))
tab_model(fit3)
```

# PLZs with large amount of change

```{r}
sep3_agg_plz <- sep3 %>% 
  st_drop_geometry() %>% 
  group_by(PLZ) %>% 
  summarize(n_diff = sum(diff),
            n = n()) %>% 
  ungroup() %>% 
  mutate(diff_share = n_diff / n) %>% 
  arrange(desc(diff_share))
```

```{r, layout="l-body-outset"}
sep3_agg_plz_geo <- plz_20_10_centr %>% 
  right_join(sep3_agg_plz)

sep3_agg_plz_geo %>% 
  tm_shape() +
  tm_dots(size = "n", col = "diff_share", palette = "-RdYlGn",
          scale = .5,  shape = 19)
```

```{r, layout="l-body-outset"}
sep3_agg_plz_geo %>% 
  filter(n > 2) %>% 
  filter(diff_share > 0.3) %>% 
  tm_shape() +
  tm_dots(size = 2, col = "diff_share", palette = "-RdYlGn",
          scale = .5,  shape = 19,
          popup.vars = c("n", "n_diff", "diff_share"))
```

```{r}
sep3_diffs <- sep3 %>% 
  filter(ssep1_d != ssep3_d) %>% 
  mutate(diff = as.numeric(ssep1_d) - as.numeric(ssep3_d))
```

```{r}
highest <- sep3_agg_plz %>% 
  filter(PLZ %in% c(8610, 5442, 1243, 8604, 6020, 7323, 7503, 8712, 4058, 8274, 5745, 8004, 8048)) %>% 
  arrange(desc(diff_share))

highest %>% 
  summarize(mean = mean(diff_share))

highest %>% 
  ggplot(aes(x = diff_share)) + 
  geom_histogram()
```

```{r}
# Alterszentrum am Buechberg AG
# Bernardastrasse 3 | 5442 Fislisbach
check = st_as_sf(st_sfc(st_point(c(2664359.750, 1255020.875), dim = "XY"), crs = 2056))
# building klas 1110

# Altersheim Im Grund
# Asylstrasse 15, 8610 Uster
check = st_as_sf(st_sfc(st_point(c(2697198, 1245338), dim = "XY"), crs = 2056))
# building klas NA
# Alternative address for Altersheim Im Grund
# Wagerenstrasse 20, 8610 Uster
check = st_as_sf(st_sfc(st_point(c(2697256.250, 1245379.625), dim = "XY"), crs = 2056))
# building klas NA

# Résidence la Louvière
# E.M.S. Résidence pour personnes âgées
# Route de La-Louvière 18 1243 Presinge
check = st_as_sf(st_sfc(st_point(c(2508767.750, 1119285.875), dim = "XY"), crs = 2056))
# building klas 1110

# Alp Betagtenzentrum
# Haldenstrasse 49, 6020 Emmenbrücke
check = st_as_sf(st_sfc(st_point(c(2663065.482, 1214196.587), dim = "XY"), crs = 2056))
# building is of klas 1122 - wouldn't be found to as collective household :/

# Alters und Pflegeheim Promulins
# Suot Staziun 7, 7503 Samedan
check = st_as_sf(st_sfc(st_point(c(2786918.500, 1156589.250), dim = "XY"), crs = 2056))
# gisid 1521275
# buildid 898806723
# building is of klas 1122 - wouldn't be found to as collective household :/
# but online it's 1130? Wohngebäude für Gemeinschaften
# https://map.geo.admin.ch/?time=None&lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bfs.gebaeude_wohnungs_register,ch.swisstopo.zeitreihen,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_opacity=1,1,1,0.8&layers_visibility=true,false,false,false&layers_timestamp=,18641231,,&E=2786918.50&N=1156589.25&zoom=10
# https://api.geo.admin.ch/rest/services/ech/MapServer/ch.bfs.gebaeude_wohnungs_register/190134295_0/extendedHtmlPopup?lang=en

check_join <- st_join(check, sep3, join = st_nearest_feature)

nearest <- st_nearest_feature(check, sep3)
distance <- st_distance(check, sep3[nearest, ], by_element = TRUE)
check_join$distance <- distance
rm(nearest, distance)

# to retrieve buildid
sep3_full <- read_dta("../SNC_Swiss-SEP2/FINAL/DTA/ssep3_full.dta") %>% 
  select(gisid, buildid)

# external data from GWR to get build class
buclassfloor <- read_dta("../SNC_Swiss-SEP2/data-raw/buclassfloor/gwrgws_buclassfloor.dta") %>% 
  rename(buildid = egid)

# external data from statpop to get build class
r18_bu_orig <- read_dta("../SNC_core/data-raw/statpop/r18_bu_orig.dta")
# View(r18_bu_orig)

# building class in statpop
sep3_full %>% 
  filter(gisid == check_join$gisid) %>% 
  left_join(r18_bu_orig)

# building class in GWR
sep3_full %>% 
  filter(gisid == check_join$gisid) %>% 
  left_join(buclassfloor)
```

```{r eval=FALSE}
# # https://www.bfs.admin.ch/bfs/de/home/register/gebaeude-wohnungsregister/publikationen.assetdetail.7008785.html
# 
# 1130 Wohngebäude für Gemeinschaften
# Diese Klasse umfasst:
#     Wohngebäude, in denen bestimmte Personen gemeinschaftlich wohnen, einschliesslich der Wohnungen für ältere Menschen, Studenten, Kinder und andere soziale Gruppen, z.B. Altersheime, Heime für Arbeiter, Bruderschaften, Waisen, Obdachlose usw.
# 
# 1264 Krankenhäuser und Facheinrichtungen des Gesundheitswesens
# Diese Klasse umfasst:
#   - Einrichtungen, die Kranken oder Verletzten ärztliche und pflegerische Betreuung bieten
#   - Sanatorien, Krankenhäuser für chronisch Kranke und Pflegeheime, psychiatrische Kliniken,
#   Krankenhausapotheken, Entbindungseinrichtungen, Sozialzentren für Mutter und Kind
#   - Universitätskliniken, Krankenhäuser in Strafvollzugs- und Untersuchungshaftanstalten und Militärkrankenhäuser
#   - Einrichtungen für Wärmebehandlung, Thalassotherapie, Heilgymnastik, Bluttransfusion, Muttermilchsammlung,
#   veterinäre Behandlung usw.
#   - Einrichtungen, die älteren Menschen, Behinderten usw. Wohnung/Unterkunft sowie pflegerische oder ärztliche Betreuung bieten
# 
# 1275 Andere Gebäude für die kollektive Unterkunft
# Diese Klasse umfasst:
#   - Strafvollzugs- und Untersuchungshaftanstalten, Armee- Polizei- und Feuerwehrunterkünfte


r18_collective <- r18_bu_orig %>% 
  filter(r18_gklas == 1130) %>% 
  # filter(r18_gklas %in% c(1130, 1264, 1275) %>% 
  select(-r18_cant, -r18_cant_sh,
         -r18_ecoord_h, -r18_ncoord_h, 
         -r18_plzz,
         -r18_gklas, -r18_fgkod, -r18_buildper, 
         -r18_nrfloor, -r18_nrdwell, 
         -r18_quarter, -r18_comm, -r18_buildcat) %>% 
  select(-r18_nrpers_total, -r18_nrpers_perm) %>% 
  # filter(!is.na(r18_ncoord)) %>% 
  # filter(!is.na(r18_ecoord)) %>% 
  st_as_sf(coords = c("r18_ecoord", "r18_ncoord"), 
           crs = 2056,
           remove = TRUE)
```



